version: '3.8'

services:
  app:
    build: .
    ports:
      - "${PORT}:3000"
    env_file: .env.docker
    
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - app-network
  