version: '3.8'

services:
  mongo:
    image: mongo:6
    ports:
      - "27017:27017" 
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    container_name: visiplus-source-mongo
    restart: unless-stopped
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge
