version: '3.8'

services:
  app:
    image: nailsmith78/jlarpy:latest
    ports:
      - "${PORT}:3000"
    env_file: .env.docker
    # environment:
    #    - NODE_ENV=development
    #    - PORT=${PORT}
    #    - MONGODB_URI=${MONGODB_URI}
    #    - JWT_SECRET=${JWT_SECRET}
    #    - JWT_EXPIRES_IN=20d
    #    - CORS_ORIGIN=*
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - app-network

  