version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGODB_URI=mongodb://mongo:27017/visiplus  # Utilise le nom du service "mongo" au lieu de "localhost"
      - JWT_SECRET=your-super-secret-jwt-key-at-least-32-characters-long
      - JWT_EXPIRES_IN=20d
      - CORS_ORIGIN=*
    container_name: visiplus-source-node
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - app-network

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"  # Expose le port 27017 sur votre machine hôte (optionnel si vous n'avez pas besoin d'y accéder depuis l'extérieur)
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    container_name: visiplus-source-mongo
    restart: unless-stopped
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge
