version: '3.8'
# si on souhaite utilise un environnement de prod autre que render

services:
  app:
    image: nailsmith78/jlarpy:latest
    ports:
      - "${PORT}:3000"
    env_file: .env.docker
   
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - app-network

  