name: CI/CD Pipeline with Tests , build, push on dockerHub si PR dev -> master

on:
  push:
    branches: ["development"]
  pull_request:
    branches: ["master"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
      
      # - name: Debug environment variables
      #   run: |
      #       echo "JWT_SECRET length: ${#JWT_SECRET}"  # Affiche la longueur (doit être >= 32)
      #       if [ ${#JWT_SECRET} -lt 32 ]; then
      #         echo "❌ JWT_SECRET est trop court ou non défini !"
      #         exit 1
      #       else
      #         echo "✅ JWT_SECRET est valide (longueur: ${#JWT_SECRET})"
      #       fi
        env:
            JWT_SECRET: ${{ secrets.JWT_SECRET }}

      - name: Run unit tests
        run: npm test
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}      # Injecte le secret
          MONGODB_URI: ${{ secrets.MONGODB_URI }}    # Injecte l'URI MongoDB
          NODE_ENV: test                              # Définit l'environnement
  
  test-git-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Debug github pull Request
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "github.event_name: ${{ github.event_name }}"
            echo "github.event.pull_request.merged: ${{ github.event.pull_request.merged }}"
            echo "github.event.pull_request.base.ref: ${{ github.event.pull_request.base.ref }}"
            echo "github.event.pull_request.head.ref: ${{ github.event.pull_request.head.ref }}"
            
            # github.event.pull_request.merged == true on ne teste pas ici car ce n'est pas forcément un merge
            echo "resultat condition: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'master' && github.event.pull_request.head.ref == 'development' }}"
          else
            echo "Event is not a pull request"
            echo "github.event_name: ${{ github.event_name }}"
          fi
  docker-build:
    runs-on: ubuntu-latest
    needs: test
    if: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'master' && github.event.pull_request.head.ref == 'development' }}
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: nailsmith78/jlarpy:latest

###### ne sert pas ici car pas d'environement serveur non payant (heroku payant et d'autres), j'ai pris render  
###### je n'utiliserais donc pas ici l'image construite dans docker Hub pour cette etude de cas
  # deploy:
  #   needs: test-and-build  
  #   if: ${{ github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'master' && github.event.pull_request.head.ref == 'development' }}
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Deploy to server via SSH
  #       uses: appleboy/ssh-action@v1
  #       with:
  #         host: ${{ secrets.SSH_HOST }}
  #         username: ${{ secrets.SSH_USERNAME }}
  #         key: ${{ secrets.SSH_PRIVATE_KEY }}
  #         script: |
  #           docker stop visiplus-source-node 2>/dev/null || true
  #           docker rm visiplus-source-node 2>/dev/null || true
  #           docker pull nailsmith78/jlarpy:latest
  #           docker run -d \
  #             --name visiplus-source-node \
  #             --network app-network \
  #             -p ${{ secrets.PORT }}:${{ secrets.PORT }} \
  #             -e MONGODB_URI=${{ secrets.MONGODB_URI }} \
  #             -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
  #             nailsmith78/jlarpy:latest